
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_NAME=teddylist
    depends_on:
      - postgres
    volumes:
      - .:/api
      - /api/node_modules

  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teddylist
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
